name: Backend Continuous Integration

on:
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch
    paths:
      - './starter/backend/**'  # Only trigger if files in the backend directory change
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
        working-directory: ./starter/backend
      - name: Install dependencies
        run: |
          cd ./starter/backend
          pipenv install

      - name: Run linting
        run: |
          cd ./starter/backend
          pipenv run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
        working-directory: ./starter/backend
      - name: Install dependencies
        run: |
          cd ./starter/backend
          pipenv install

      - name: Run tests
        run: |
          cd ./starter/backend
          pipenv run test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]  # This job will only run if lint and test jobs succeed
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker build
        run: |
          docker build --tag mp-backend:latest .
        working-directory: ./starter/backend